### ISSUE TITLE
Missing shared objects (.so)

### ISSUE THREAD

**Issue by fnivek** [binary42/MultiTrackHSV#2]
There are no .so files in the MultiTrackHSV/Libraries/Opencv3.1/lib. .so files are in the .gitignore so they would have never been pushed up to the repository. Since they are not a generic build of opencv 3.1 they should be pushed up to the repository. Either remove the .so entry in the .gitignore, explicitly add each .so file and then push them up, or including instructions/script (or maybe cmake can do this automatically) for compiling opencv with correct flags.

**Comment by binary42** [comment]
added stripped versions of x64 opencv libs. compiles with third party libs for image types and qt functionality.

**Comment by binary42** [comment]
Recompile Opencv without CUDA
